### PR TITLE
Improved UI, Native API Calls, and ViewModel

### PR DESCRIPTION
**Pull request by Sidneys1**

### CODE REVIEW

**Comment by Donkie** [comment]
Hey it's you again!
Great job!

**Comment by Sidneys1** [comment]
Thanks! Don't forget to merge.

**Comment by Donkie** [comment]
I must say I love the UI, great job!

**Comment by Donkie** [comment]
Looks like you've done this in the new C# 6, I am unable to get hold of VS2015, and this whole MVVM thing is greek for me, could you recode this with C# 5 instead?

**Comment by Sidneys1** [comment]
Thanks! MVVM is pretty easy once you get the hang of it. I've reissued a pull request with the C# 6.0 features removed.

**Pull request merged**
